# Generated by Django 5.2.7 on 2025-10-07 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=150)),
                ('study_type', models.CharField(max_length=50)),
                ('cover_letter', models.FileField(upload_to='uploads/')),
                ('cv', models.FileField(upload_to='uploads/')),
                ('passport_file', models.FileField(upload_to='uploads/')),
                ('personal_image', models.ImageField(upload_to='uploads/')),
                ('highest_degree', models.FileField(upload_to='uploads/')),
                ('transcript', models.FileField(upload_to='uploads/')),
                ('recommendation_letter1', models.FileField(upload_to='uploads/')),
                ('recommendation_letter2', models.FileField(upload_to='uploads/')),
                ('english_proficiency', models.FileField(upload_to='uploads/')),
                ('medical_exam', models.FileField(upload_to='uploads/')),
                ('conduct_certificate', models.FileField(upload_to='uploads/')),
                ('intro_video', models.FileField(upload_to='uploads/')),
                ('research_proposal', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('additional_certificates', models.TextField(blank=True, null=True)),
                ('other_files', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'application',
                'ordering': ['-created_at'],
            },
        ),
    ]