# Generated by Django 5.2.7 on 2025-10-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
    ]